---
ACTION_ACTIONLINT_ARGUMENTS:
  - -shellcheck=
APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DISABLE:
  - SPELL
DISABLE_LINTERS:
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - TERRAFORM_TERRASCAN
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
