---
APPLY_FIXES: all

DISABLE:
  - COPYPASTE
  - SPELL
  - ACTION
    #  - TERRAFORM_TERRASCAN
    #  - TERRAFORM_TFLINT
    #  - REPOSITORY_CHECKOV
    #  - REPOSITORY_KICS

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
