---
APPLY_FIXES: all
DISABLE:
  - SPELL
DISABLE_LINTERS:
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TFLINT

ACTION_ACTIONLINT_ARGUMENTS:
  - -shellcheck=

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
GITHUB_STATUS_REPORTER: true
