---
APPLY_FIXES: all

DISABLE:
  - COPYPASTE
  - SPELL
  - ACTION
DISABLE_LINTERS:
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TFLINT
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_GRYPE

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
GITHUB_STATUS_REPORTER: true
