---
APPLY_FIXES: all
DISABLE:
  - SPELL
DISABLE_LINTERS:
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TFLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
GITHUB_STATUS_REPORTER: true
