---
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.3
    hooks:
      - id: remove-crlf
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--config=./.tflint.hcl
      - id: terraform_tfsec
        args:
          - --args=--tfvars-file=terraform.auto.tfvars
      - id: terraform_validate
      - id: terraform_checkov
      - id: terraform_docs
      - id: terrascan
        args:
          - --args=--non-recursive
          - --args=--policy-type=azure
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '1000']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--format, github]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/anderseknert/pre-commit-opa
    rev: v1.5.1
    hooks:
      - id: opa-fmt
        args: [policies, -w]
      - id: opa-check
        args: [policies, -b]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
      - id: gitlint-ci
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.7
    hooks:
      - id: ripsecrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
