---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--config=./.tflint.hcl
      - id: terraform_tfsec
        args:
          - --args=--tfvars-file=terraform.auto.tfvars
      - id: terraform_validate
      - id: terraform_checkov
      - id: terraform_docs
      - id: terrascan
        args:
          - --args=--non-recursive
          - --args=--policy-type=azure
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: no-commit-to-branch
      - id: end-of-file-fixer
      - id: trailing-whitespace
