name: Branch Delete
on:
  - delete
jobs:
  delete:
    if: github.event.ref_type == 'branch' && [[ ! -z "${{ secrets.CONTROLLER_REPOSITORY_FULL_NAME }}" ]]
    runs-on: ubuntu-latest
    steps:
      - name: Branch Delete
        env:
          GITHUB_TOKEN:  ${{ secrets.CONTROLLER_TOKEN }}
        run: |
          if [[ ! -z "${{ secrets.CONTROLLER_REPOSITORY_FULL_NAME }}" ]]
          then
            gh workflow run tf-plan-apply.yml --ref main -R ${{ secrets.CONTROLLER_REPOSITORY_FULL_NAME }}
          fi
