name: Branch Create
on:
  - create
jobs:
  create:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Branch Create
        env:
          GITHUB_TOKEN:  ${{ secrets.CONTROLLER_TOKEN }}
        run: |
          if [[ ! -z "${{ secrets.CONTROLLER_REPOSITORY_FULL_NAME }}" ]]
          then
            gh workflow run tf-plan-apply.yml --ref main -R ${{ secrets.CONTROLLER_REPOSITORY_FULL_NAME }}
          fi
