---
name: FortiDevSec DAST

on:          # yamllint disable-line rule:truthy
    push:
        branches: [main]
        paths:
            - '**.tf'
    pull_request:
        branches: [main]
        paths:
            - '**.tf'

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}

jobs:
    build:
        name: DevSec DAST
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: DAST
              run: |
                  env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
                  docker pull registry.fortidevsec.forticloud.com/fdevsec_dast:latest
                  docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_dast:latest
