---
name: 'debug'

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  action:
    name: 'action'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    outputs:
      action: ${{ steps.terraform.outputs.action }}
    steps:
      - id: terraform
        name: ${{ github.ref_name }} deployed is ${{ vars.DEPLOYED }}
        shell: bash
        run: |
          if [[ ${{ vars.DEPLOYED }} == 'true' ]]
          then
            echo 'action=apply' >> ${GITHUB_OUTPUT}
          else
            echo 'action=destroy' >> ${GITHUB_OUTPUT}
          fi

  apply:
    #needs: [action]
    #if: needs.action.outputs.action == 'apply'
    if: vars.DEPLOYED == 'true'
    name: 'apply'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: apply
        run: echo "apply"

#  destroy:
#    #needs: [action]
#    #if: needs.action.outputs.action != 'apply'
#    if: {{ vars.DEPLOYED != 'true'
#    name: 'destroy'
#    runs-on: ubuntu-latest
#    environment:
#      name: ${{ github.ref_name }}
#    steps:
#      - name: destroy
#        run: echo "destroy"

#  apply-destroy:
#    needs: [action]
#    runs-on: ubuntu-latest
#    environment:
#      name: ${{ github.ref_name }}
#    steps:
#      - name: apply
#        if: needs.terraform.outputs.action == 'apply'
#        run: echo "apply"
#      - name: destroy
#        if: needs.terraform.outputs.action != 'apply'
#        run: echo "destroy"
