---
name: Auto approve PRs by dependabot

on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  autoapprove:
    name: Auto-Approve a PR by dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: cognitedata/auto-approve-dependabot-action@595b523194b98a03da1f521d9524266e6cdf7cea
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
