---
name: Scan Code for Secrets

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

permissions:
  contents: none

jobs:
  check-for-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@8507d8897b8f9a5d6ce1decbf0a00ac96045f93e
        with:
          fail_on_error: true
          reporter: github-pr-review # Change reporter.
      - name: Commit back .secrets.baseline (if it was missing)
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d
        with:
          commit_message: "build(detect-secrets): Commit the newly-generated .secrets.baseline file"
