---
name: Pre-commit auto-update

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - name: TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: tfsec
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Checkov
        run: pip3 install checkov

      - name: terraform-docs
        run: |
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          install terraform-docs /usr/local/bin && rm terraform-docs

      - name: Terrascan
        run: |
          curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
          tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
          chmod +x terrascan
          install terrascan /usr/local/bin && rm terrascan

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Hashicorp Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: pre-commit
        run: pip install pre-commit

      - name: pre-commit autoupdate
        run: git switch -c pre-commit-autoupdate && pre-commit autoupdate --color never && pre-commit run --all-files --color never

      - uses: peter-evans/create-pull-request@v5
        with:
          branch: pre-commit-autoupdate
          delete-branch: true
          title: Update pre-commit hooks
          body: Update versions of pre-commit hooks to latest version.
