---
name: Pre-commit auto-update

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: TFLint GitHub Action
        uses: pauloconnor/tflint-action@v0.0.2

      - name: tfsec action
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Checkov GitHub Action
        run: pip3 install checkov

      - name: terraform-docs-gh-actions
        uses: terraform-docs/gh-actions@v1

      - name: Terrascan IaC scanner
        uses: tenable/terrascan-action@v1

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Hashicorp Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - uses: browniebroke/pre-commit-autoupdate-action@main

      - uses: peter-evans/create-pull-request@v5
        with:
          title: Update pre-commit hooks
          body: Update versions of pre-commit hooks to latest version.
