---
name: terraform-docs

on: # yamllint disable-line rule:truthy
  pull_request:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push:
            "false"
            # token: ${{ secrets.PAT }}
            # github-token: ${{ secrets.PAT }}

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: 18

      - run: npm install markdown-table-formatter -g

      - name: Markdown lint table formatter
        run: markdown-table-formatter README.md

      - name: Create Pull Request with applied fixes
        id: cpr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          commit-message: "[terraform-docs] Apply linters automatic fixes"
          title: "[terraform-docs] Apply linters automatic fixes"
          labels: bot
