---
name: 'Terraform Action'

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  terraform:
    name: 'action'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    outputs:
      action: ${{ steps.terraform.outputs.action }}
    steps:
      - id: terraform
        name: "${{ github.ref_name }} deployed is ${{ vars.AZURE_DEPLOYED }}"
        shell: bash
        run: |
          env
          if [[ "${{ vars.AZURE_DEPLOYED }}" == "true" ]]
          then
            echo 'action=apply' >> ${GITHUB_OUTPUT}
          else
            echo 'action=destroy' >> ${GITHUB_OUTPUT}
          fi

  plan:
    needs: [terraform]
    if: needs.terraform.outputs.action == 'apply'
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    env:
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        env:
          AZURE_TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_TFSTATE_STORAGE_ACCOUNT_NAME }}
          AZURE_TFSTATE_CONTAINER_NAME: ${{ secrets.AZURE_TFSTATE_CONTAINER_NAME }}
          AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: terraform init -backend-config="storage_account_name=${AZURE_TFSTATE_STORAGE_ACCOUNT_NAME}" -backend-config="container_name=${AZURE_TFSTATE_CONTAINER_NAME}" -backend-config="resource_group_name=${AZURE_RESOURCE_GROUP_NAME}" -backend-config="use_oidc=true" -input=false

      - name: Terraform Format
        id: format
        run: terraform fmt -check

      - name: Terraform Plan
        id: tf-plan
        env:
          TF_VAR_AZURE_RESOURCE_GROUP_NAME: "${{ github.event.repository.name }}-${{ github.ref_name }}"
          TF_VAR_AZURE_REGION: ${{ secrets.TF_VAR_AZURE_REGION }}
          TF_VAR_AZURE_USERNAME: ${{ secrets.TF_VAR_AZURE_USERNAME }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: |
          export exitcode=0
          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else
            exit 0
          fi

      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

      - name: Create String Output
        id: tf-plan-string
        run: |
          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      #- name: Push Terraform Output to PR
      #  if: github.ref != 'refs/heads/main'
      #  uses: actions/github-script@v6
      #  env:
      #    SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    script: |
      #      const body = `${process.env.SUMMARY}`;
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: body
      #       })

  apply:
    name: 'Terraform Apply'
    if: needs.terraform.outputs.action == 'apply'
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    needs: [terraform,plan]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        env:
          AZURE_TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_TFSTATE_STORAGE_ACCOUNT_NAME }}
          AZURE_TFSTATE_CONTAINER_NAME: ${{ secrets.AZURE_TFSTATE_CONTAINER_NAME }}
          AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: terraform init -backend-config="storage_account_name=${AZURE_TFSTATE_STORAGE_ACCOUNT_NAME}" -backend-config="container_name=${AZURE_TFSTATE_CONTAINER_NAME}" -backend-config="resource_group_name=${AZURE_RESOURCE_GROUP_NAME}" -backend-config="use_oidc=true" -input=false

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Terraform Apply
        id: apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: terraform apply -auto-approve tfplan

  destroy:
    name: 'Terraform Destroy'
    needs: [terraform]
    if: needs.terraform.outputs.action == 'destroy'
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        env:
          AZURE_TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_TFSTATE_STORAGE_ACCOUNT_NAME }}
          AZURE_TFSTATE_CONTAINER_NAME: ${{ secrets.AZURE_TFSTATE_CONTAINER_NAME }}
          AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: terraform init -backend-config="storage_account_name=${AZURE_TFSTATE_STORAGE_ACCOUNT_NAME}" -backend-config="container_name=${AZURE_TFSTATE_CONTAINER_NAME}" -backend-config="resource_group_name=${AZURE_RESOURCE_GROUP_NAME}" -backend-config="use_oidc=true" -input=false

      - name: Terraform Destroy
        id: destroy
        env:
          TF_VAR_AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          TF_VAR_AZURE_REGION: ${{ secrets.TF_VAR_AZURE_REGION }}
          TF_VAR_AZURE_USERNAME: ${{ secrets.TF_VAR_AZURE_USERNAME }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: |
          terraform destroy -auto-approve
