---
name: 'tf-plan-apply-destroy.yml'

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  terraform-plan:
    if: ${{ vars.DEPLOYED == 'true' }}
    name: 'debug'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: debug
        run: env

