---
name: 'tf-plan-apply-destroy.yml'

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  #  apply-or-destroy:
  #  name: 'apply or destroy'
  #  runs-on: ubuntu-latest
  #  environment:
  #    name: ${{ github.ref_name }}
  #  outputs:
  #    action: ${{ steps.action.outputs.action }}
  #  steps:
  #    - name: Set Action to apply or destroy
  #      run: |
  #        if [ ${{ vars.DEPLOYED }} == "true" ]; then
  #          echo "action=apply" >> $GITHUB_OUTPUT
  #        else
  #          echo "action=destroy" >> $GITHUB_OUTPUT
  #        fi

  terraform-apply:
    #needs: [apply-or-destroy]
    if: ["${{ vars.DEPLOYED }}" == "true"]
    name: 'apply'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: apply
        run: echo ${{ vars.DEPLOYED }}

  terraform-destroy:
    # needs: [apply-or-destroy]
    if: ["${{ vars.DEPLOYED }}" != "true"]
    name: 'destroy'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: destroy
        run: echo ${{ vars.DEPLOYED }}
