---
name: 'Application Unit Tests'

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  terraform-unit-tests:
    name: 'Terraform Unit Tests'
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          output_format: cli
          output_file_path: console,results.sarif
          soft_fail: true
          skip_check: CKV_AZURE_93,CKV_AZURE_160,CKV_AZURE_119

      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.0.0

      - name: Init TFLint
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: Setup Go environment
        uses: actions/setup-go@v4

      - name: Go Version
        run: go version

      - name: github-action-terratest
        uses: cloudposse/github-action-terratest@main

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
