---
name: 'Terraform Unit Tests'

on:
  push:

jobs:
  terraform-unit-tests:
    name: 'Terraform Unit Tests'
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          output_format: cli
          output_file_path: console,results.sarif
          soft_fail: true
          skip_check: CKV_AZURE_93,CKV_AZURE_160,CKV_AZURE_119

