---
name: 'Yamllint'
on: push  # yamllint disable-line rule:truthy
permissions:
  contents: none
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
